--------------------------------------------------------
-- Archivo creado  - lunes-enero-03-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body PCK_HELADOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "BASTIAN_2"."PCK_HELADOS" as    
    PROCEDURE PRC_GENERARPEDIDO(V_RUT IN VARCHAR2) IS
        V_PEDIDOS NUMBER;
        CODE VARCHAR2(100);
        E_RROR VARCHAR2(500);
    BEGIN 
        SELECT
            COUNT(PEDIDO_ID)
        INTO
            V_PEDIDOS
        FROM PEDIDO
        WHERE CLIENTE_ID = FN_BUSCARCLIENTE(V_RUT);  
        IF V_PEDIDOS = 0 THEN
            INSERT INTO PEDIDO VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 'ACTIVO', 0, FN_BUSCARCLIENTE(V_RUT));
        ELSIF V_PEDIDOS > 0 THEN
                UPDATE PEDIDO SET ESTADO = 'CANCELADO'
                WHERE CLIENTE_ID = FN_BUSCARCLIENTE(V_RUT) AND ESTADO = 'ACTIVO';
            INSERT INTO PEDIDO VALUES(SEQ_PEDIDO.NEXTVAL, SYSDATE, 'ACTIVO', 0, FN_BUSCARCLIENTE(V_RUT));
        END IF;
    EXCEPTION WHEN OTHERS THEN
        CODE := SQLCODE;
        E_RROR := SQLERRM;
        EXECUTE IMMEDIATE 'BEGIN PRC_REGISTRARLOGERROR(:A, :B, :C); END;' USING 'PRC_GENERARPEDIDO', CODE, E_RROR;   
    END PRC_GENERARPEDIDO;


    PROCEDURE PRC_AGREGARHELADO(V_HELADO_CODE IN VARCHAR2, V_RUT IN VARCHAR2) IS 
        V_HELADO_ID NUMBER;
        V_PEDIDO_ID NUMBER;
        V_ESTADO VARCHAR2(100);
        V_CANTIDAD NUMBER;
        CODE VARCHAR2(100);
        E_RROR VARCHAR2(100);
    BEGIN
        SELECT
            HELADO_ID
        INTO
            V_HELADO_ID
        FROM HELADO
        WHERE HELADO_CD = V_HELADO_CODE; 
        SELECT
            ESTADO,
            PEDIDO_ID
        INTO
            V_ESTADO,
            V_PEDIDO_ID
        FROM PEDIDO
        WHERE CLIENTE_ID = FN_BUSCARCLIENTE(V_RUT) AND ESTADO = 'ACTIVO';
        SELECT 
            COUNT(HELADO_ID)
        INTO
            V_CANTIDAD
        FROM PEDIDODETALLE
        WHERE PEDIDO_ID = V_PEDIDO_ID;
        IF V_ESTADO = 'ACTIVO' AND V_CANTIDAD = 0 THEN
            INSERT INTO PEDIDODETALLE VALUES(SEQ_PEDIDODETALLE.NEXTVAL, V_PEDIDO_ID, V_HELADO_ID, 1);
        ELSE
            UPDATE PEDIDODETALLE
            SET CANTIDAD = V_CANTIDAD + 1
            WHERE PEDIDO_ID = V_PEDIDO_ID;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        CODE := SQLCODE;
        E_RROR := SQLERRM;
        EXECUTE IMMEDIATE 'BEGIN PRC_REGISTRARLOGERROR(:A, :B, :C); END;' USING 'PRC_GENERARPEDIDO', CODE, E_RROR;    
    END PRC_AGREGARHELADO;

    PROCEDURE PRC_TOTALIZARPEDIDO(V_RUT VARCHAR2) IS 
        V_TOTAL NUMBER := 0;
        V_PEDIDO_ID NUMBER;
        V_PRECIO_BASE NUMBER;
        CODE VARCHAR2(100);
        E_RROR VARCHAR2(100);
    BEGIN
        SELECT 
            PEDIDO_ID
        INTO
            V_PEDIDO_ID
        FROM PEDIDO
        WHERE CLIENTE_ID = FN_BUSCARCLIENTE(V_RUT) AND ESTADO = 'ACTIVO';
        FOR PRODUCTO IN (SELECT HELADO_ID, CANTIDAD FROM PEDIDODETALLE WHERE PEDIDO_ID =V_PEDIDO_ID) 
        LOOP
            SELECT
                PRECIOBASE
            INTO
                V_PRECIO_BASE
            FROM HELADO
            WHERE HELADO_ID = PRODUCTO.HELADO_ID;
            V_TOTAL := V_TOTAL + (PRODUCTO.CANTIDAD * V_PRECIO_BASE);
        END LOOP;
        UPDATE PEDIDO SET VALOR = V_TOTAL, ESTADO = 'VENDIDO' WHERE PEDIDO_ID = V_PEDIDO_ID;
    EXCEPTION WHEN OTHERS THEN
        CODE := SQLCODE;
        E_RROR := SQLERRM;
        EXECUTE IMMEDIATE 'BEGIN PRC_REGISTRARLOGERROR(:A, :C, :B); END;' USING 'PRC_GENERARPEDIDO', CODE, E_RROR;    
    END PRC_TOTALIZARPEDIDO; 

    PROCEDURE PRC_LIMPIATABLA IS
    BEGIN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE PEDIDODETALLE ';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE PEDIDO';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE LOGVENTA';
    END PRC_LIMPIATABLA;
END PCK_HELADOS;

/
